### ISSUE TITLE
Investigate app crash after add child under 5

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#129]

**Comment by rkodev** [comment]
@keymane There seems to be a bug on with the database encryption. see log below
``` E/Database: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
    net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method) ``
``` 
: Couldn't open drishti.db for writing (will try read-only):
    net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method) ```

``` E/Database: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
    net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method) ```

Failure to read the database file is leading to a null pointer when saving these values

``` E/AndroidRuntime: FATAL EXCEPTION: pool-10-thread-1
    Process: org.smartregister.wcaro, PID: 3462
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.smartregister.commonregistry.CommonPersonObject.getCaseId()' on a null object reference ```

**Comment by cagulas** [comment]
Not crashing for me anymore. Will reopen if it re-occurs, but have registered a handful of children and it's not crashing.
